services:
  feed-service:
    build: ./services/feed-service
    networks: [ lab ]
#    healthcheck:
#      test: [ "CMD", "wget", "-qO-", "http://localhost:8081/health" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5

  glitchmesh:
    build:
      context: ..
      dockerfile: lab/Dockerfile.glitchmesh
    ports:
      - "9000:9000"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./proxy.yaml:/app/proxy.yaml:ro
    depends_on:
      feed-service:
        condition: service_started
    networks: [ lab ]
#    healthcheck:
#      test: [ "CMD", "wget", "-qO-", "http://localhost:9000/" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5

  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      GLITCHMESH_URL: http://glitchmesh:9000
      FEED_SERVICE_NAME: feed-service
    depends_on:
      glitchmesh:
        condition: service_started
    networks: [ lab ]
#    healthcheck:
#      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/health" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5

networks:
  lab:
    driver: bridge
